In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
np.random.seed(666)

In [4]:
X = np.random.random(size=(1000,10))

In [6]:
true_theta = np.arange(1,12,dtype=float)

In [8]:
m = len(X)

In [17]:
X_b = np.hstack([np.ones((m,1)),X])

In [20]:
y = X_b.dot(true_theta)+np.random.normal(size=1000)

In [22]:
## 损失函数
def J(theta,X_b,y):
    return np.sum((X_b.dot(theta) - y)**2)/len(X_b)

In [24]:
def dJ(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta)-y)*2./len(y)

In [34]:
def dJ_math(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta)-y)*2./len(y)

In [64]:
def dJ_debug(theta,X_b,y,epsilon=1e-8):
    m = len(theta)
    res = np.empty(m)
    for i in range(m):
        theta_plus = theta.copy()
        theta_plus[i] += epsilon
        theta_minus = theta.copy()
        theta_minus[i] -= epsilon
        res[i] = (J(theta_plus,X_b,y) - J(theta_minus,X_b,y))/(2*epsilon)
    return res

In [32]:
dJ_math(true_theta,X_b,y)

array([-0.01707541, -0.01975592,  0.0023443 , -0.03300947, -0.01991536,
        0.00455009, -0.00615756, -0.01060135,  0.0136495 , -0.00604455,
        0.0053788 ])

In [47]:
dJ_debug(true_theta,X_b,y)

array([-0.01707541, -0.01975592,  0.0023443 , -0.03300947, -0.01991536,
        0.00455009, -0.00615756, -0.01060135,  0.0136495 , -0.00604455,
        0.0053788 ])

In [59]:
def gradient_desc(dJ,X_b,y,inital_theta=np.zeros(len(X_b[0])),eta=0.01,n_iter=1e4,epsilon=1e-8):
    theta = inital_theta
    cur_iter = 0
    while cur_iter < n_iter:
        cur_gradient = dJ(theta,X_b,y)
        last_theta = theta
        theta = theta - eta * cur_gradient
        if abs(J(theta,X_b,y) - J(last_theta,X_b,y)) < epsilon:
            break
        cur_iter += 1
    return theta

In [62]:
%time gradient_desc(dJ_math,X_b,y)

CPU times: user 1.12 s, sys: 119 ms, total: 1.23 s
Wall time: 686 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [65]:
%time gradient_desc(dJ_debug,X_b,y)

CPU times: user 7.92 s, sys: 770 ms, total: 8.69 s
Wall time: 4.45 s


array([ 1.1251597 ,  2.05312521,  2.91522496,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])