In [1]:
from sklearn import linear_model

/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
reg = linear_model.LinearRegression()

In [3]:
linear_model.LinearRegression?

In [4]:
import numpy as np

In [5]:
from sklearn.datasets import load_boston

/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
load_boston?>

SyntaxError: invalid syntax (<ipython-input-6-96fa3c4fd0da>, line 1)

In [7]:
load_boston?

In [8]:
load_boston.DESCR

AttributeError: 'function' object has no attribute 'DESCR'

In [9]:
load_boston.DESCR()

AttributeError: 'function' object has no attribute 'DESCR'

In [10]:
load_boston.data

AttributeError: 'function' object has no attribute 'data'

In [11]:
load_boston().data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [12]:
load_boston().target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [13]:
data = load_boston()

In [14]:
import sklearn

In [15]:
data.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [16]:
data.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [17]:
X_train,X_test,y_train,y_test = sklearn.model_selection.train_test_split(data.data,data.target)

In [18]:
X_train

array([[8.37000e-02, 4.50000e+01, 3.44000e+00, ..., 1.52000e+01,
        3.96900e+02, 5.39000e+00],
       [8.49213e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        8.34500e+01, 1.76400e+01],
       [7.61620e-01, 2.00000e+01, 3.97000e+00, ..., 1.30000e+01,
        3.92400e+02, 1.04500e+01],
       ...,
       [2.90900e-01, 0.00000e+00, 2.18900e+01, ..., 2.12000e+01,
        3.88080e+02, 2.41600e+01],
       [2.06080e-01, 2.20000e+01, 5.86000e+00, ..., 1.91000e+01,
        3.72490e+02, 1.25000e+01],
       [7.83932e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 1.32200e+01]])

In [19]:
X_test

array([[3.58400e-02, 8.00000e+01, 3.37000e+00, ..., 1.61000e+01,
        3.96900e+02, 4.67000e+00],
       [4.11300e-02, 2.50000e+01, 4.86000e+00, ..., 1.90000e+01,
        3.96900e+02, 5.29000e+00],
       [7.02259e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.19980e+02, 1.57000e+01],
       ...,
       [1.00623e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        8.13300e+01, 1.96900e+01],
       [1.43200e-02, 1.00000e+02, 1.32000e+00, ..., 1.51000e+01,
        3.92900e+02, 3.95000e+00],
       [5.26930e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.82000e+02, 4.63000e+00]])

In [20]:
y_train

array([34.9, 14.5, 22.8, 43.8, 19.9, 18.9, 19.9, 19.5, 35.1, 17.4, 21.6,
       21.7, 50. , 35.4, 13.3, 11.7, 19. , 20.5, 13.8, 18.5,  9.6, 20.6,
       13. , 17.8, 16.1, 18.7, 13.8, 14.9, 33.2, 21.4, 36.2, 33.4, 17.1,
       17.1, 19.9, 13.9, 33.8, 20.2, 18.8, 23.8, 24.6, 15.2, 26.2, 20.9,
       21.4, 14.5, 16.6,  7.4, 19.8, 19.9, 23.4, 20.1, 37. , 31.6, 50. ,
       21.2, 19.4, 35.2, 20.3, 17.5, 22.9, 36.5, 31.5, 22. , 23.3, 33. ,
       24.1, 20. , 46.7, 50. , 10.8,  8.8, 22.9,  7.2, 14.9, 50. , 33.4,
       15.6, 21. , 25. , 11. , 17. ,  7. , 28.4, 15.1, 31.7,  8.5, 42.3,
       29. , 22.6, 25.2, 30.3, 15.3, 28.5, 25. , 17.8, 22.6, 23.2,  8.4,
       26.6, 19.3, 20.8, 15.2, 30.1, 33.3, 36.2, 16.7, 24.3, 14.1,  7.2,
       19.5,  8.4, 23. , 22.2, 29.9, 24.5, 37.9, 21.1, 15. , 50. , 14.1,
       33.1, 17.8, 21.9, 50. , 29.6, 16.5, 24.8, 13.8, 20.4, 43.1, 19.4,
       16.4, 23.3, 17.1, 13.8, 26.6, 42.8, 13.9, 19.3, 20.7, 21.9, 22.9,
       30.5, 48.3, 20.3, 24. , 24.4, 17.2, 31.2, 21

In [21]:
y_test

array([23.5, 28. , 14.2, 45.4, 12.5, 20.8, 50. , 48.5, 48.8, 15.6, 34.7,
       10.9, 27. , 17.4, 24.7, 19.4, 24.8, 27.5, 28.6, 30.1, 23.7, 20. ,
       43.5, 36.4, 15.4, 24.6, 20.4,  6.3, 22.5, 21.1, 19.4, 19.6, 11.7,
       19.5, 17.2,  7.2, 13.4, 25.1, 22.2, 19.3, 15.7, 13.2,  9.5, 23. ,
       16.5, 23.8, 26.4, 17.5, 20.4, 29.4, 20.1, 20.9,  5.6, 22. , 22. ,
       41.3, 13.1, 20. , 24.1, 10.5, 29. , 13.4, 22.2, 13.4, 50. , 19.4,
       21.2, 23.6, 20.1, 26.5, 27.1, 15.6, 50. , 35.4, 23.1, 31.5, 23.6,
       46. , 13.5, 12.7, 18.9, 28.7, 26.4, 13.3, 50. , 23.3, 17.5, 37.3,
       16.3, 32.9, 10.9,  8.8, 22. , 24.2, 21.4, 23.9, 18.4, 10.2, 24.4,
       18.5, 27.5, 14.6, 14.6, 24.4, 19.7, 30.8,  9.7, 22.1, 14.3, 23.9,
       17.8, 22.8, 50. , 15. , 23.1, 13.3, 36. , 18.8, 50. , 24. , 22.5,
       12. , 28.7, 26.6, 14.1, 31.6, 50. ])

In [22]:
from sklearn import linear_model

In [23]:
reg = linear_model.LinearRegression()

In [24]:
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
reg.coef_

array([-1.03342406e-01,  4.03831149e-02, -1.81097082e-02,  2.61072916e+00,
       -1.94335701e+01,  3.76932400e+00, -7.15871948e-03, -1.42629601e+00,
        2.63125844e-01, -8.62938109e-03, -9.41989023e-01,  9.55689039e-03,
       -4.55234007e-01])

In [26]:
sklearn.model_selection.train_test_split?

In [27]:
from sklearn import svm

In [28]:
svm?

In [29]:
reg?

In [30]:
reg.score(X_train,y_train)

0.73689670961536

In [31]:
reg.score(X_test,y_test)

0.7363214457921892

In [32]:
reg.predict(X_test)

array([30.43271958, 28.37097214, 17.93042557, 38.06485385, 19.38064212,
       17.59447975, 36.00048255, 41.25670464, 39.84666948, 13.17213767,
       30.10974955, 14.05532773, 31.62767227, 15.80315773, 25.04847508,
       25.90506365, 26.12780032, 31.76690381, 28.31942615, 29.27401526,
       27.57365925, 18.39932995, 38.47684949, 33.0717229 , 14.47038631,
       28.80175366, 20.77847766, 11.87327268, 29.35957476, 20.57055972,
       22.98793444, 18.98735781, 15.72822123, 20.11423582, 15.7150958 ,
       17.96794606, 13.6175483 , 29.76105235, 19.70280826, 21.20678853,
       14.31119302,  9.83747447, 13.43046067, 23.68823361, 22.81921562,
       25.05864644, 22.6152986 , 17.35787361, 19.45779973, 30.61651418,
       20.63015539, 22.27020363, 12.55171975, 25.33933521, 29.06052982,
       32.13584508, 14.58630215, 23.21126392, 21.17812507, 13.03889388,
       32.19288641, 16.39156604, 24.35763155, 14.5297252 , 44.01094173,
       23.70632619, 23.60666612, 30.26526905, 23.94801469, 25.51

In [33]:
reg = linear_model.LinearRegression()

In [34]:
reg.fit([[1,1],[2,2],[3,3]],[1,2,3])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
reg.coef_

array([0.5, 0.5])

In [36]:
reg.predict([4,4])

ValueError: Expected 2D array, got 1D array instead:
array=[4 4].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [37]:
reg.predict([[4,4],[5,5.1]])

array([4.  , 5.05])

In [38]:
reg.score([[4,4],[5,5.1]],[4,5])

0.9950000000000002

In [39]:
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
reg.score(X_train,y_train)

0.73689670961536

In [41]:
reg = linear_model.Ridge(alpha=.5)

In [42]:
reg.fit(X_train,y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [43]:
reg.score(X_train,y_train)

0.7354960520351141

In [44]:
alphas = 0.5** i for i in range(0,10)

SyntaxError: invalid syntax (<ipython-input-44-c57d85d49012>, line 1)

In [45]:
range?

In [46]:
alphas = 0.5**i for i in range(0,10,1)

SyntaxError: invalid syntax (<ipython-input-46-44f9d3db8fd8>, line 1)

In [47]:
alphas = (0.5**i for i in range(0,10,1))

In [48]:
alphas = (0.5**i for i in range(10,0,-1))

In [49]:
alphas

<generator object <genexpr> at 0x12143ae58>

In [50]:
np.array(alphas)

array(<generator object <genexpr> at 0x12143ae58>, dtype=object)

In [51]:
)

SyntaxError: invalid syntax (<ipython-input-51-a35077a93b18>, line 1)

In [52]:
_

array(<generator object <genexpr> at 0x12143ae58>, dtype=object)

In [53]:
alphas = list(alphas)

In [54]:
alphas

[0.0009765625,
 0.001953125,
 0.00390625,
 0.0078125,
 0.015625,
 0.03125,
 0.0625,
 0.125,
 0.25,
 0.5]

In [55]:
alphas = (0.5**i for i in range(10,-10,-1))

In [56]:
alphas = list(alphas)

In [57]:
alphas

[0.0009765625,
 0.001953125,
 0.00390625,
 0.0078125,
 0.015625,
 0.03125,
 0.0625,
 0.125,
 0.25,
 0.5,
 1.0,
 2.0,
 4.0,
 8.0,
 16.0,
 32.0,
 64.0,
 128.0,
 256.0,
 512.0]

In [58]:
regs = (linear_model.Ridge(alpha=a) for a in alphas)

In [59]:
regs

<generator object <genexpr> at 0x125acd5e8>

In [60]:
str(reg._coef for reg in regs)

'<generator object <genexpr> at 0x125acd660>'

In [61]:
str(list(reg._coef for reg in regs))

AttributeError: 'Ridge' object has no attribute '_coef'

In [62]:
regs

<generator object <genexpr> at 0x125acd5e8>

In [63]:
list(regs)

[Ridge(alpha=0.001953125, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.00390625, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.0078125, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.015625, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.03125, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.0625, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=0.125, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=None, solver='auto', tol=0.001),
 Ridge(alpha=

In [64]:
linear_model.Ridge?

In [65]:
reg.fit(X_train,y_train) for reg in regs

SyntaxError: invalid syntax (<ipython-input-65-19e871aeef88>, line 1)

In [66]:
reg.fit(X_train,y_train) for reg in list(regs)

SyntaxError: invalid syntax (<ipython-input-66-f26cfa3b0966>, line 1)

In [67]:
for reg in regs:
    reg.fit(X_train,y_train)

In [68]:
np.array(alphas)

array([9.765625e-04, 1.953125e-03, 3.906250e-03, 7.812500e-03,
       1.562500e-02, 3.125000e-02, 6.250000e-02, 1.250000e-01,
       2.500000e-01, 5.000000e-01, 1.000000e+00, 2.000000e+00,
       4.000000e+00, 8.000000e+00, 1.600000e+01, 3.200000e+01,
       6.400000e+01, 1.280000e+02, 2.560000e+02, 5.120000e+02])

In [69]:
scores = (reg.score(X_test,y_test) for reg in list(regs))

In [70]:
scores

<generator object <genexpr> at 0x125acd840>

In [71]:
list(scores)

[]

In [72]:
regs[0]

TypeError: 'generator' object is not subscriptable